# Generated by Django 2.2 on 2022-06-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'City_info',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Course_Info',
            },
        ),
        migrations.CreateModel(
            name='Trainer_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer_Name', models.CharField(max_length=50)),
                ('Trainer_Password', models.CharField(max_length=50)),
                ('Trainer_Email', models.CharField(max_length=50)),
                ('Trainer_city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.CityInfo')),
            ],
            options={
                'db_table': 'Trainer_Registration_info',
            },
        ),
        migrations.CreateModel(
            name='Trainer_Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.CourseInfo')),
                ('tname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Trainer_Register')),
            ],
            options={
                'db_table': 'Trainer_Data',
            },
        ),
    ]
