# Generated by Django 2.2 on 2022-06-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_register',
            name='Trainer_Age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='trainer_register',
            name='Trainer_Phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
